version: "3.9"
services:
  nginx:
    build: .
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "./nginx/frontend:/usr/share/nginx/html/"
      - "./nginx/logs:/var/log/nginx/"
      - "./nginx/video:/video"
      - "./nginx/stats:/root/nginx-rtmp-module-dev/stat.xsl/"
    restart: always
    ports:
      - "8080:8080"
      - "1935:1935"

  logging_database:
    image: timescale/timescaledb:latest-pg14
    volumes:
      - "./monitor/database:/docker-entrypoint-initdb.d"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
      - POSTGRES_DB=logging
    ports:
      - "5432:5432"

volumes:
  portainer_data: